### PR TITLE
Introducing in-memory services

### PR DESCRIPTION
**Pull request by ajs6f**
https://github.com/trellis-ldp/trellis/issues/440

First draft, needs tests

NOT YET FOR MERGING

### CODE REVIEW

**Comment by acoburn** [comment]
While this will be very useful for the test code, it _might_ be useful in other contexts, too. So, would it make sense to put these classes in their own `./component` jar? I.e. `./components/simple`.

I'd be happy to add the gradle parts if you'd like

**Comment by ajs6f** [comment]
Yeah, I can see that making sense. Let me finish the basic work here (writing tests now) and we can send it wherever we want. I want to get back to the µprofile app-- just doing a little warm-up here since I haven't seen Trellis in quite a while!

**Comment by ajs6f** [comment]
@acoburn This just needs some tests for the binary side. Do we have anything like `ResourceServiceTests` I could use for that? Otherwise, I have no freakin' idea what happened to Git there. Those look like commits in `master` _and_ duplicated commits in this branch? You have any idea how I could have done that?

**Comment by acoburn** [comment]
maybe if you did a merge from the master branch? you can try rebasing off of master again. Alternatively, you could squash your commits and then cherry-pick them into a clean branch.

As for the binary tests, there's nothing stand-alone for that, but that's a good idea for something to add.

**Comment by ajs6f** [comment]
I guess we can just squash this when it gets merged, right? 

I'll file a ticket for more tests, and meanwhile I'll add some simple tests here and be done.

**Comment by ajs6f** [comment]
Okay, that's the last bit of testing for the mo, and rebasing cured the Git weirdity.

Let me know if you want more tests before merging. Otherwise, I'll wait to hear from you about [whether and where you want to move this](https://github.com/trellis-ldp/trellis/pull/450#issuecomment-517319417).

**Pull request merged**
