### PR TITLE
Various small syntax cleanups

### PR DESCRIPTION
**Pull request by ajs6f**
Mostly removing the use of Objects::nonNull and Objects::isNull, with a few other bits thrown in.

This PR only covers the stack up through `-http` and ignores all the backends and optional components. They can be handled in separate PRs to avoid crazy levels of line-change too fast.

### CODE REVIEW

**Comment by ajs6f** [comment]
The Travis build failed for nothing to do with this PR:
```
The command "~/bin/install-jdk.sh --target "/home/travis/openjdk11" --workspace "/home/travis/.cache/install-jdk" --feature "11" --license "GPL" --cacerts" failed and exited with 1 during .
```

**Comment by acoburn** [comment]
The Java11 downloader/installer tends to fail for a while right around the time of an update (11.0.3 was just released). It should be operational again soon, but that's pretty much out of our hands.

**Comment by ajs6f** [comment]
I figured it was some silliness like that.

**Comment by acoburn** [comment]
LGTM. I'll double-check the JDK11 build tomorrow. By then it should have sorted itself out

**Comment by ajs6f** [comment]
Sounds good. I'll be out-of-touch tomorrow but back on Sunday. Feel free to reject anything you think makes the code _less_ idiomatic, because my opinions have been known to be a bit surreal at times.

**Pull request merged**
