### PR TITLE
Add default implementations for http.core interfaces

### LINKED ISSUE #449: Create default implementations for http.core interfaces
Two new interfaces in the http layer (`http.core.EtagGenerator` and `http.core.TimemapGenerator`) have no default implementations, which makes it harder to use these as injectable CDI beans, especially since they are now required parts of the `ServiceBundler` interface.

Related question: should these beans have a `@Default` and/or `@ApplicationScoped` annotation assigned?

### PR DESCRIPTION
**Pull request by acoburn**
Resolves #449

### CODE REVIEW

**Comment by ajs6f** [comment]
I don't see any place these types are getting injected-- is that already in the code base?

**Comment by acoburn** [comment]
At present, we just have Dropwizard, which doesn't do injection (c.f. #209). This PR does update the manual creation of these objects from anonymous `new EtagGenerator() { }` to `new DefaultEtagGenerator()`.

One consideration here is that the existing interfaces both have default methods, which constitute the entirety of the implementation  -- that code could legitimately be moved into these `Default*Generator` classes, leaving the interfaces much cleaner.

**Comment by ajs6f** [comment]
No, we have the `trellis-cassandra` app and we have the µprofile app on the way, so we do need to think about how this stuff gets injected. In these particular cases, I think we should be okay if they appear in the `ServiceBundler` type in the usual way. (Required components always appear there by policy.) 

As for where to put the default behavior, I entirely agree that we should factor it over to the concrete default classes, especially since I took a look and the logic is not trivial. There is some real and serious business going on there.

**Comment by acoburn** [comment]
In fact, the `trellis-cassandra` app is very much what prompted this PR.

I will refactor the impl code into the implementing classes. A new commit is on the way.

**Pull request merged**
