### PR TITLE
Fix for219

### PR DESCRIPTION
**Pull request by ajs6f**
I'm reoffering this commit, because the current `master` doesn't build for me for the exact same reasons as didn't `trellis-219`, so whatever happens with https://github.com/trellis-ldp/trellis/pull/229, I would like to get this into `master`.

### CODE REVIEW

**Comment by ajs6f** [comment]
Urg, just realized I took _your_ commit with mine. I meant to just cherry-pick mine, but actually, there's nothing wrong with yours, I don't think. So merging either this 'un or #229 would let me get back on the road to look at #237 .

**Comment by acoburn** [comment]
How about if I just cherry-pick this commit into master? I agree that either way, it should make its way into the master branch.

**Comment by ajs6f** [comment]
Totally cool with me. That should let me build and roll forward.

**Comment by acoburn** [comment]
Fixed via https://github.com/trellis-ldp/trellis/commit/87038289581aa263ca6c06d1552491008a518324

**Pull request closed without merging**
