### PR TITLE
 Minor adjustments to CDI machinery

### PR DESCRIPTION
**Pull request by ajs6f**
Minor adjustments to CDI machinery

### CODE REVIEW

**Comment by ajs6f** [comment]
The second commit says "typesafety"!

**Comment by acoburn** [comment]
LGTM. Let me know when you think this is ready to commit

**Comment by ajs6f** [comment]
Will do. Was in JSON-LD WG, now in CLAW call, hope to be done after lunch.

**Comment by ajs6f** [comment]
If the CI don't scream, let's ship it. I've got a semi-functional CDI-driven Cassandra example OTW, but it's a bit ragged yet.

**Comment by acoburn** [comment]
The updated SNAPSHOT artifacts have been pushed to the Sonatype repo.

**Pull request merged**
